app:
  datasourse:
    main:
      password: 'postgres'
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/amigocode
      username: 'postgres'
      pool-size: 30


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/amigocode
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always